### ISSUE TITLE
Port submitted?

### ISSUE THREAD

**Issue by Lechindianer** [idefix6/gogs-freebsdport#1]
Hi there,

as far as I have seen, you haven't submitted your port to the mailing list yet. Do you intend to create a official FreeBSD port?

Thanks

**Comment by mfechner** [comment]
Am 01.04.2015 um 10:58 schrieb Pascal Schmid:

> Hi there,
> 
> as far as I have seen, you haven't submitted your port to the mailing
> list yet. Do you intend to create a official FreeBSD port?

as the port is far away from being finished I have not send a PR.
If the port is finished and working fine, I will send a PR to get it
into the freebsd port.
But currently I have no time to continue on the port.

Next problem is that gogs requires the config file on a relative path to
the binary. As this will be changed in the next version, I will wait
here till this is changed.

If you would like to help, I'm very happy about pull requests.

Gruß
Matthias

## 

"Programming today is a race between software engineers striving to
build bigger and better idiot-proof programs, and the universe trying to
produce bigger and better idiots. So far, the universe is winning." --
Rich Cook

**Comment by dR3b** [comment]
Are there any news about the port?

**Comment by mfechner** [comment]
Please see here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205283
There are in comments links to already prebuild package of gogs.
